### ISSUE TITLE
App does not warn user if some images in sequence are not geotagged causing errors at final step

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#15]
If some (>1) images processed (or video frames) has no geotags, user sees message, "some of your images are missing geotags. Do you want to 1) discard (skip add gpx step), or 2) upload gpx track (goes to gpx track)".

This test case has images with some geotagged, some not geotagged images: https://drive.google.com/drive/folders/1LzJqdG4pEvez9yfT2BNYaytCLVEQWRUk?usp=sharing)

Does not currently produce above expected behaviour currently (https://drive.google.com/file/d/1nTAD4THQUaSL9jgJLohOoBTosItWi_tK/view?usp=sharing)

By allowing use to continue with some images not geotagged it causes error at final step (when final step images are process) -  screen goes white and this error occurs:

```
Calculation points issue TypeError: Cannot read property 'setDistance' of undefined
    at discardPointsBySeconds (C:\Users\david\Downloads\mtp-desktop-uploader\app\scripts\utils\/index.ts:148:13)
    at calculatePoints (C:\Users\david\Downloads\mtp-desktop-uploader\app\scripts\/image.ts:185:25)
    at nextTask (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:4576:27)
    at next (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:4584:13)
    at next (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:321:20)
    at C:\Users\david\Downloads\mtp-desktop-uploader\app\scripts\/image.ts:151:9
    at wrapper (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:268:20)
    at iteratorCallback (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:495:17)
    at cb (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:321:20)
```

**Comment by himynamesdave** [comment]
Warning still not shown to user if geotags missing (discard or add track)

See this test case, where some images are missing geotags: https://drive.google.com/drive/u/1/folders/1JsYZRfHxuKxx908Ms0FYzv7nlHzZ6mMq

**Comment by himynamesdave** [comment]
closing as done
