### ISSUE TITLE
If images have no GPS on upload, app shows white screen

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#37]
When 0 images have geotags app hits white screen and user cannot proceed

https://drive.google.com/drive/u/1/folders/10waXSs6mgEotnmG1zepy0VJr9SocZu3h

Terminal prints error

```
Calculation points issue TypeError: Cannot read property 'setDistance' of undefined
    at discardPointsBySeconds (C:\Users\david\Downloads\mtp-desktop-uploader\app\scripts\utils\/index.ts:149:13)
    at calculatePoints (C:\Users\david\Downloads\mtp-desktop-uploader\app\scripts\/image.ts:209:25)
    at nextTask (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:4576:27)
    at next (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:4584:13)
    at next (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:321:20)
    at C:\Users\david\Downloads\mtp-desktop-uploader\app\scripts\/image.ts:175:9
    at wrapper (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:268:20)
    at iteratorCallback (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:495:17)
    at cb (C:\Users\david\Downloads\mtp-desktop-uploader\node_modules\async\dist\async.js:321:20)
    at C:\Users\david\Downloads\mtp-desktop-uploader\app\scripts\/image.ts:166:18
```

**Comment by himynamesdave** [comment]
closing as done
